spring:
  application:
    name: pedidos
  datasource:
    url: jdbc:h2:mem:pedidos;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    # Necesario para que data.sql se ejecute DESPUES de que Hibernate cree las tablas
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always

logging:
  level:
    com.empresa.pedidos: DEBUG
